spring:
  security:
     oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8181/realms/Joseph
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: joseph-rest
      principle-attribute: joseph-rest

keycloak:
  realm: Joseph
  domain: localhost:8080
  adminClientId: admin_cli
  adminClientSecret: qopVlLFaBMZSz9OVUGqlf2fmaMEMmyyi
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}
